# -*- coding: utf-8 -*-
# Event descriptions taken from this webpage: https://developers.onelogin.com/docs/event-fields#section-event-type-ids
from __future__ import absolute_import
event_id_to_description = {
    '1': 'App added to role',
    '2': 'App removed from role',
    '3': 'Acting user assumed user',
    '4': 'Role assigned to user',
    '5': 'User logged in to OneLogin',
    '6': 'User login to OneLogin failed',
    '7': 'User logged out of OneLogin',
    '8': 'User logged in to app',
    '9': 'User failed app login',
    '10': 'User requested new password',
    '11': 'User changed password',
    '12': 'User unlocked',
    '13': 'User created',
    '14': 'User updated',
    '15': 'User deactivated',
    '16': 'User activated',
    '17': 'User deleted',
    '18': 'Admin approved password request',
    '19': 'User locked',
    '20': 'User limit reached',
    '21': 'User suspended',
    '22': 'User registered OTP device',
    '23': 'User triggered bulk operation',
    '24': 'User deregistered OTP device',
    '25': 'Provisioning exception',
    '26': 'Provisioning event',
    '27': 'User downloaded browser certificate',
    '28': 'User recently removed',
    '29': 'User logged out of app',
    '30': 'Updated payment info',
    '31': 'Failed update to payment info',
    '32': 'User reactivated',
    '33': 'User imported from directory',
    '34': 'User requested access to app',
    '35': 'User locked out of app',
    '36': 'User lost OTP device',
    '37': 'User requested join',
    '38': 'App reached user limit',
    '39': 'Connector broken',
    '40': 'User unlocked OTP device',
    '41': 'Active Directory Connector started',
    '42': 'Active Directory Connector stopped',
    '43': 'Active Directory Connector configuration reloaded',
    '44': 'Active Directory Connector notification',
    '45': 'Active Directory Connector exception',
    '46': 'Active Directory Connector failed over',
    '47': 'Active Directory Connector exception',
    '48': 'User imported',
    '49': 'Update to user failed',
    '50': 'User rejected',
    '51': 'User created in app',
    '52': 'User updated in app',
    '53': 'User suspended in app',
    '54': 'User reactivated in app',
    '55': 'User deleted in app',
    '56': 'Unmatched users',
    '59': 'User linked in app',
    '61': 'User suspension failed in app',
    '62': 'User reactivation failed in app',
    '63': 'User deletion failed in app',
    '64': 'User creation failed in app',
    '65': 'User update failed in app',
    '66': 'No users to import',
    '67': 'Directory import exception',
    '68': 'User authenticated by RADIUS',
    '69': 'User rejected by RADIUS',
    '70': 'Privilege granted to account',
    '71': 'Privilege revoked from account',
    '72': 'Privilege granted to user',
    '73': 'Privilege revoked from user',
    '74': 'User added a trusted IdP',
    '75': 'User removed a trusted IdP',
    '76': 'User modified a Trusted IdP',
    '77': 'User failed to login to app via assertion proxy',
    '78': 'User logged into app via assertion proxy',
    '79': 'User failed to provision in directory',
    '80': 'User created in directory',
    '81': 'User updated in directory',
    '82': 'User suspended in directory',
    '83': 'User reactivated in directory',
    '84': 'User deleted in directory',
    '85': 'Could not authenticate to app',
    '86': 'User failed remote authentication',
    '87': 'User viewed secure note',
    '88': 'User edited secure note',
    '89': 'User deleted secure note',
    '100': 'Self-registration requested for user',
    '101': 'Self-registration approved for user',
    '102': 'Self-registration denied for user',
    '105': 'SMS failure',
    '110': 'Acting user updated user login information',
    '111': 'Acting user attempted to update user login information',
    '112': 'User changed default trusted IdP',
    '113': 'Directory import started',
    '114': 'Directory import finished',
    '115': 'User invited',
    '116': 'User creation failed',
    '117': 'Directory sync run ID',
    '118': 'SAML assertion consumer service failed',
    '120': 'User unlocked in directory',
    '121': 'Scriptlet error',
    '124': 'Safe Entitlements Provisioning',
}
